source: ./jekyll
exclude:
  - "react"

layouts_dir: ./jekyll/_layouts

collections_dir: ./jekyll/my_collections

collections:
  post:
    output: true
    # permalink: /:collection/:name
    permalink: /:collection/:path