exclude: [
  "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/",
  "react/",
]

url: "https://ssw1295.github.io" # the base hostname & protocol for your site

title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections_dir: collections

collections:
  entry:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: "index.md"
      type: "pages"
    values:
      layout: "page-main"
  - scope:
      path: ""
      type: "entry"
    values:
      layout: "page-entry"
  - scope:
      path: "json"
      type: "pages"
    values:
      layout: "page-json"
      permalink: /:path